const { gql } = require("apollo-server");

const typeDefs = gql`
type Books{
  id:Int
  name:String
  numbering:Int
  sort:String
  synopsis:String
}
type AddBookResponse{
  code: Int
  message:String
  data:Books
}
input AddBook{
  name:String!
  numbering:Int
  sort:String
  synopsis:String
}
type RemoveBookResponse{
    id:Int!
    code: Int
    message:String
}
type Query {
    showAllBooks: [Books]
  }

type Mutation {
    addBooks(input:AddBook):AddBookResponse
    removeBooks(id:Int!):RemoveBookResponse
  }

`;

module.exports =  typeDefs 